(()=>{'use strict';
const $=(s,p=document)=>p.querySelector(s), $$=(s,p=document)=>[...p.querySelectorAll(s)];
let audioCtx=null,soundReady=false,lastSound=0,soundEnabled=true;
function unlockSound(){if(!audioCtx){try{audioCtx=new(window.AudioContext||window.webkitAudioContext)();soundReady=true;audioCtx.resume?.();sfx('unlock')}catch(e){}}else{audioCtx.resume?.();soundReady=true}}
function sfx(kind='tap',freq=520,gain=.025){if(!soundEnabled||!soundReady||!audioCtx)return;const now=performance.now();if(now-lastSound<45&&kind!=='unlock')return;lastSound=now;const map={unlock:[360,.035,'sine'],tap:[680,.045,'sine'],reveal:[420,.045,'triangle'],tick:[300,.018,'square'],goal:[720,.08,'triangle'],gallery:[500,.06,'sine'],call:[820,.075,'sine'],close:[250,.05,'sine'],theme:[560,.06,'sine'],menu:[440,.045,'triangle']};const m=map[kind]||[freq,gain,'sine'];const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=m[2];o.frequency.setValueAtTime(m[0],audioCtx.currentTime);if(kind==='goal')o.frequency.exponentialRampToValueAtTime(980,audioCtx.currentTime+.12);if(kind==='theme')o.frequency.exponentialRampToValueAtTime(820,audioCtx.currentTime+.08);g.gain.setValueAtTime(0,audioCtx.currentTime);g.gain.linearRampToValueAtTime(m[1],audioCtx.currentTime+.008);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.16);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.18)}
['pointerdown','touchstart','keydown'].forEach(e=>window.addEventListener(e,unlockSound,{once:true,passive:true}));
window.addEventListener('visibilitychange',()=>{if(audioCtx?.state==='suspended')audioCtx.resume?.()});
window.addEventListener('load',()=>{setTimeout(()=>{$('#loader')?.classList.add('done');sfx('goal')},2300)});

const loaderPercent=$('#loaderPercent');const loaderBar=$('.loader-line span');if(loaderPercent&&loaderBar){const t0=performance.now();const loaderTick=t=>{const p=Math.min((t-t0)/2150,1),e=1-Math.pow(1-p,3);loaderPercent.textContent=Math.round(e*100)+'%';loaderBar.style.width=(e*100)+'%';if(p<1)requestAnimationFrame(loaderTick)};requestAnimationFrame(loaderTick)}
// Theme switcher
let lightTheme=false;try{lightTheme=localStorage.getItem('portfolio-theme')==='light'}catch(e){}
function setTheme(light){lightTheme=light;document.body.classList.toggle('light-theme',light);document.documentElement.style.colorScheme=light?'light':'dark';$$('.theme-toggle').forEach(b=>{b.innerHTML=light?'<span>🌙</span>':'<span>☀</span>';b.title=light?'الوضع الليلي':'الوضع النهاري';b.setAttribute('aria-pressed',String(light))});try{localStorage.setItem('portfolio-theme',light?'light':'dark')}catch(e){};sfx('theme')}
$$('.theme-toggle').forEach(b=>b.addEventListener('click',()=>setTheme(!lightTheme)));setTheme(lightTheme);
const progress=$('.scroll-progress span');window.addEventListener('scroll',()=>{const h=document.documentElement.scrollHeight-innerHeight;if(progress)progress.style.width=(scrollY/Math.max(h,1)*100)+'%'},{passive:true});
const revealItems=$$('.reveal');const revealObserver=new IntersectionObserver(entries=>{entries.forEach((entry)=>{if(entry.isIntersecting){entry.target.classList.add('revealed');entry.target.style.transitionDelay=((entry.target.dataset.delay||0))+'ms';sfx('reveal')}else{entry.target.classList.remove('revealed')}})},{threshold:.14,rootMargin:'0px 0px -70px'});revealItems.forEach((x,i)=>{x.dataset.delay=(i%5)*80;revealObserver.observe(x)});
// Stats counters
function count(el,end,decimals=0,duration=1200){if(el.dataset.done)return;el.dataset.done='1';const start=performance.now();let last=-1;const tick=t=>{const p=Math.min((t-start)/duration,1),e=1-Math.pow(1-p,3),value=end*e;if(decimals)el.textContent=value.toFixed(decimals);else{const n=Math.floor(value);if(n!==last){last=n;sfx('tick');}el.textContent=n}if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick)}
$$('[data-count]').forEach(el=>{new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)count(el,+el.dataset.count,0,1300)}),{threshold:.65}).observe(el)});
$$('[data-decimal]').forEach(el=>{new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)count(el,+el.dataset.decimal,2,1200)}),{threshold:.65}).observe(el)});
// Skills
$$('.skill').forEach(skill=>{const bar=$('em',skill),num=$('.skill-number',skill),level=+skill.dataset.level;new IntersectionObserver(es=>es.forEach(e=>{if(!e.isIntersecting||skill.dataset.done)return;skill.dataset.done='1';let start=performance.now();bar.style.width=level+'%';const tick=t=>{const p=Math.min((t-start)/1300,1),v=Math.round(level*(1-Math.pow(1-p,3)));num.textContent=v+'%';if(p<1)requestAnimationFrame(tick)};requestAnimationFrame(tick);sfx('goal')}),{threshold:.5}).observe(skill)});
const output=$('.output-track span');if(output)new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){output.style.width='100%';sfx('goal')}}),{threshold:.6}).observe(output);
// 3D card
const card=$('#playerCard');if(card){card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(1100px) rotateY(${x*10}deg) rotateX(${y*-10}deg) translateY(-6px)`});card.addEventListener('pointerleave',()=>card.style.transform='');card.addEventListener('pointerdown',()=>sfx('tap'))}
// Magnetic buttons
$$('.magnetic').forEach(el=>{el.addEventListener('pointermove',e=>{if(innerWidth<900)return;const r=el.getBoundingClientRect();el.style.transform=`translate(${(e.clientX-(r.left+r.width/2))*.1}px,${(e.clientY-(r.top+r.height/2))*.1}px)`});el.addEventListener('pointerleave',()=>el.style.transform='');el.addEventListener('click',()=>sfx(el.closest('#contact')?'call':'tap'))});
// Gallery
const lightbox=$('#lightbox'),lbImg=$('#lightbox img'),lbCount=$('.lightbox-count');const gallery=$$('.gallery-item');gallery.forEach((item,i)=>item.addEventListener('click',()=>{lbImg.src=item.dataset.full;lbCount.textContent=`${String(i+1).padStart(2,'0')} / ${String(gallery.length).padStart(2,'0')}`;lightbox.classList.add('open');sfx('gallery')}));$('.lightbox-close')?.addEventListener('click',()=>{lightbox.classList.remove('open');sfx('close')});lightbox?.addEventListener('click',e=>{if(e.target===lightbox){lightbox.classList.remove('open');sfx('close')}});window.addEventListener('keydown',e=>{if(e.key==='Escape')lightbox.classList.remove('open')});
// Phone links
$$('a[href^="tel:"]').forEach(a=>a.addEventListener('click',()=>sfx('call')));
// Mobile menu
const menu=$('.mobile-menu');$('.menu-btn')?.addEventListener('click',()=>{menu.classList.add('open');sfx('menu')});$('.mobile-close')?.addEventListener('click',()=>{menu.classList.remove('open');sfx('close')});$$('.mobile-menu a').forEach(a=>a.addEventListener('click',()=>{menu.classList.remove('open');sfx('tap')}));
$('#mobileThemeToggle')?.addEventListener('click',()=>setTheme(!lightTheme));
// Achievements: sequential, scroll-triggered reveal
const achievements=$$('.achievement-card');const achievementSection=$('#achievements');if(achievements.length&&achievementSection){let sequenceTimer=[];const resetAchievements=()=>{sequenceTimer.forEach(clearTimeout);sequenceTimer=[];achievements.forEach(a=>a.classList.remove('sequence-in'))};const ao=new IntersectionObserver(es=>{es.forEach(e=>{if(e.isIntersecting){resetAchievements();achievements.forEach((card,i)=>{sequenceTimer.push(setTimeout(()=>{card.classList.add('sequence-in');sfx(i===0?'goal':'reveal')},i*260))})}else{resetAchievements()}})},{threshold:.2});ao.observe(achievementSection)}
// Subtle section ambience if GSAP is available
if(window.gsap&&window.ScrollTrigger){gsap.registerPlugin(ScrollTrigger);gsap.utils.toArray('.section-head h2').forEach(h=>gsap.from(h,{y:28,opacity:0,duration:.8,ease:'power3.out',scrollTrigger:{trigger:h,start:'top 88%'}}));gsap.utils.toArray('.position-info article').forEach((el,i)=>gsap.from(el,{x:35,opacity:0,duration:.7,delay:i*.08,ease:'power3.out',scrollTrigger:{trigger:el,start:'top 90%'}}));}
})();
